
GET http://localhost:8080/products

###

POST http://localhost:8080/attributes
Content-Type: application/json

{
  "name": "Test 5"
}

###

GET http://localhost:8080/attributes

###

PUT http://localhost:8080/attributes/1649fc56-0961-4564-835c-c88e8d83cc02
Content-Type: application/json

{
  "name": "Test 90000"
}

###

POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Test 666",
  "attributeIds": ["1649fc56-0961-4564-835c-c88e8d83cc02"]
}

###

GET http://localhost:8080/products/d3eb41c9-af5a-4fa4-ab4a-e3c19e57a44a
