GET http://localhost:8080/products

###

POST http://localhost:8080/products

###

POST http://localhost:8080/products/tt

###

POST http://localhost:8080/products/repo

###

GET http://localhost:8080/products/repo

###

PUT http://localhost:8080/products/1
